# NumPy
Welcome to the fourth lesson! This Jupyter Notebook file is meant to accompany **L04 - NumPy.**

Type your solutions for each exercise in the code cells below, and then press **Shift + Enter** to execute your code. Then, check the solution video to see how you did!

### 1. Introduction to NumPy

### 2. NumPy Arrays

In [ ]:
#Imports a module of code called math. Calls custom log function 
import math 
math.log(10)

In [ ]:
#Function for random sampling, creating randomized data
import numpy as np

In [ ]:
#np.tab - Functions 
np.function 

In [1]:
import numpy as np

In [2]:
array_1 = np.array([1, 2, 3, 4, 5])
print(array_1)

[1 2 3 4 5]


<font color = 'blue'> **EXERCISE 2.1** </font>

In [4]:
#All objects in a numpy array must be the same object 
#Square brackets indicate a list of list 
import numpy as np

array_1 = np.array([ [1, 2], [3, 4], [5, 6] ])

print(array_1)
print('---') #Space
print(array_1.shape) # Print shape of array 1

[[1 2]
 [3 4]
 [5 6]]
---
(3, 2)


<font color = 'blue'> **EXERCISE 2.2** </font>

In [8]:
#Create a new array, array_b, by reshaping array_a to 6 rows and 4 columns
#Print array_b
#Use ranges, print "new york stock exchange" from array_b with a new line for each word (you will call the print function four times) 
array_a = np.array([
    ['n', 'e', 'w', 'y', '_', 's'],
    ['t', 'o', 'c', 'k', '_', 'r'],
    ['_', '_', '_', 'k', 'e', 'x'],
    ['c', 'h', 'a', 'n', 'g', 'e']
])

In [3]:
# Reshape to 6 rows and 4 columns and print
array_b = array_a.reshape(6, 4)
print(array_b)


[['n' 'e' 'w' 'y']
 ['_' 's' 't' 'o']
 ['c' 'k' '_' 'r']
 ['_' '_' '_' 'k']
 ['e' 'x' 'c' 'h']
 ['a' 'n' 'g' 'e']]


In [4]:
# Print 'new york stock exchange' from array_b (one word per line)
print(array_b[0, :3]) #0 indicates we are looking at first row. 3 we are excluding y
print(array_b[:4, 3])
print(array_b[1, 1:], array_b[2, :2])
print(array_b[4, :], array_b[5, :]) #: Indicates we want the entire 5th row

['n' 'e' 'w']
['y' 'o' 'r' 'k']
['s' 't' 'o'] ['c' 'k']
['e' 'x' 'c' 'h'] ['a' 'n' 'g' 'e']


### 3. NumPy Array Functions

<font color = 'blue'> **EXERCISE 3.1** </font>

In [5]:
#Create a new array called price_increases by subtracting current_prices from target_prices
#Print prince_increases
#Create a new array called returns by dividing price_increases by current_prices and rounding the result to 3 decimal places
#Print returns
#Print the maximum value in returns
#Print the mean returns for each industry column rounded to 3 decimal places

current_prices = np.array([
    [223.84, 113.5, 139.49],
    [113.37, 30.37, 265.31],
    [1177.98, 54.73, 42.96],
])

target_prices = np.array([
    [232.27, 112.15, 144.2],
    [122.3, 34.33, 284.14],
    [1384.89, 62.12, 43.06],
])

In [6]:
price_increases = target_prices - current_prices
print(price_increases)
print('---')

returns = np.round(price_increases / current_prices, 3)
print(returns)
print('---')

print(np.max(returns))
print('---')

print(np.round(np.mean(returns, axis=0), 3))

[[ 8.4300e+00 -1.3500e+00  4.7100e+00]
 [ 8.9300e+00  3.9600e+00  1.8830e+01]
 [ 2.0691e+02  7.3900e+00  1.0000e-01]]
---
[[ 0.038 -0.012  0.034]
 [ 0.079  0.13   0.071]
 [ 0.176  0.135  0.002]]
---
0.176
---
[0.098 0.084 0.036]


### 4. NumPy Random Tools

<font color = 'blue'> **EXERCISE 4.1** </font>

In [9]:
#Set the random seed to 99
#Generate an array of random integers between 1 and 25 named rand_array with 5 rows and 5 columns
#Print rand_array
#Choose and print a random sample of 5 numbers from the second row of rand_array with replacement
#Generate an array of ordered integers from 1 to 25 named ordered_array and reshape to 5 rows and 5 columns
#Print order_array
#Choose and print a random sample of 5 numbers from the third column of ordered_array without replacement

np.random.seed(99)

rand_array = np.random.randint(1, 26, [5, 5])
print(rand_array)
print('---')

print(np.random.choice(rand_array[1, :], 5))
print('---')

ordered_array = np.array(range(1, 26)).reshape(5, 5)
print(ordered_array)
print('---')

print(np.random.choice(ordered_array[:, 2], 5, replace=False))

[[ 2  4  9 10  9]
 [19  5  6 21  2]
 [24  4 24 18  2]
 [17  7 12 21 24]
 [ 3  1 13  9  9]]
---
[ 2  5 21  6 21]
---
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---
[13 18  8  3 23]
